#!/bin/bash

log () {
  >&2 echo "$@"
}

print_usage () {
  log "USAGE: $0 <volume_name> [backup_target] [archive_name]"
}

if [ $# -eq 0 ] || [ $# -gt 3 ]; then
  log "ERROR: Invalid argument count!"
  print_usage
  exit 1
fi

if [ -z "$1" ]; then
  log "ERROR: Missing required argument 'volume_name'!"
  print_usage
  exit 2
fi

VOLUME_NAME="$1"
BACKUP_TARGET="$(realpath ${2:-`pwd`})"
ARCHIVE_NAME="${3:-volume-backup_${VOLUME_NAME}_`date '+%Y%m%d-%H%M%S-%Z'`.tgz}"

log "INFO: Backing up volume '${VOLUME_NAME}' into '${BACKUP_TARGET}/${ARCHIVE_NAME}'..."

exec docker run --rm -v "${VOLUME_NAME}:/source_volume" -v "${BACKUP_TARGET}:/backup" alpine:latest sh -c "apk add tar &>/dev/null && tar -cvzf /backup/${ARCHIVE_NAME} -C /source_volume ."
