#!/bin/bash

are_you_sure () {
  MSG=${1:-"Are you sure to continue?"}
  read -r -p "$MSG [y/N] " response
  [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]
}

if [ "$1" == "images" ]; then
    echo "WARNING: This will remove all dangling images!"
    echo "The operation cannot be undone as data will be erased from the disk directly!"

    are_you_sure && docker image ls --filter "dangling=true" --quiet | xargs docker image rm || exit 0
elif [ "$1" == "volumes" ]; then
    echo "WARNING: This will remove all dangling volumes!"
    echo "The operation cannot be undone as data will be erased from the disk directly!"

    are_you_sure && docker volume ls --filter "dangling=true" --quiet | xargs docker volume rm || exit 0
elif [ "$1" == "networks" ]; then
    docker network prune
elif [ "$1" == "containers" ]; then
    docker container prune
else
    echo "WARNING: This will remove all local dangling images, volumes and networks!"
    echo "The operation cannot be undone as data will be erased from the disk directly!"

    if are_you_sure; then
        echo ""

        echo "Removing images..."
        docker image ls --filter "dangling=true" --quiet | xargs docker image rm
        echo ""

        echo "Removing volumes..."
        docker volume ls --filter "dangling=true" --quiet | xargs docker volume rm
        echo ""

        echo "Removing networks..."
        docker network ls --filter "dangling=true" --quiet | xargs docker network rm
        echo ""

        echo ""
    else
        exit 0
    fi
fi

echo "Done."
exit 0