#!/bin/bash

log () {
  >&2 echo "$@"
}

print_usage () {
  log "USAGE: $0 <from_container> [backup_target] [archive_name]"
}

if [ $# -eq 0 ] || [ $# -gt 3 ]; then
  log "ERROR: Invalid argument count!"
  print_usage
  exit 1
fi

if [ -z "$1" ]; then
  log "ERROR: Missing required argument 'from_container'!"
  print_usage
  exit 2
fi

FROM_CONTAINER="$1"
BACKUP_TARGET="$(realpath ${2:-`pwd`})"
ARCHIVE_NAME="${3:-container-backup_${FROM_CONTAINER}_`date '+%Y%m%d-%H%M%S-%Z'`.tgz}"
MOUNT_POINTS="$(docker inspect $FROM_CONTAINER | jq -r '.[0].Mounts | .[] | .Destination')"

log "INFO: Backing up all volumes from container '${FROM_CONTAINER}' into '${BACKUP_TARGET}/${ARCHIVE_NAME}'..."

exec docker run --rm --volumes-from "${FROM_CONTAINER}" -v "${BACKUP_TARGET}:/backup" alpine:latest sh -c "apk add tar &>/dev/null && tar -cvzf /backup/${ARCHIVE_NAME} $(echo "$MOUNT_POINTS" | awk '{ print "-C "$0" *" }' | tr '\n' ' ')"